Update Dockerfile
dfinity/icp-dev-env pull request #8
Opened 2024-04-29 09:58 UTC by letmejustputthishere

bump to latest dfx version and remove unnecessary env variable

2024-04-29 14:49 UTC, ericswanson-dfinity submitted a review, later dismissed

2024-04-30 06:27 UTC, letmejustputthishere commented
@fxgst or @ericswanson-dfinity can you please create a new release for me 😇

2024-04-30 09:23 UTC, fxgst requested changes

2024-04-30 09:23 UTC, fxgst commented on Dockerfile
> -ENV DFX_VERSION=
This needs to stay, otherwise `dfxvm` won't let you change versions.

2024-04-30 09:26 UTC, fxgst commented
Thanks for the PR. Please also bump the version in the Dockerfile in `/azle`

2024-04-30 10:02 UTC, letmejustputthishere commented on Dockerfile
> -ENV DFX_VERSION=
does this mean we have to add it to the azle dockerfile as well?

2024-05-02 07:54 UTC, fxgst commented on Dockerfile
> -ENV DFX_VERSION=
In the azle Dockerfile we just set the env variable at the line where we install dfx, so on the line after it it's not set anymore, whereas here we export it at the top to have all versions at the top, but then we need to unset it at the end of the file to make dfxvm be able to switch versions... I know I should've just used one approach consistently :D

2024-05-02 07:56 UTC, fxgst approved these changes

2024-05-02 07:56 UTC, merged